\connect join_db;

COPY aka_name FROM 'aka_name.csv' WITH (FORMAT csv);
COPY aka_title FROM 'aka_title.csv' WITH (FORMAT csv);
COPY cast_info FROM 'cast_info.csv' WITH (FORMAT csv);
COPY char_name FROM 'char_name.csv' WITH (FORMAT csv);
COPY company_name FROM 'company_name.csv' WITH (FORMAT csv);
COPY company_type FROM 'company_type.csv' WITH (FORMAT csv);
COPY comp_cast_type FROM 'comp_cast_type.csv' WITH (FORMAT csv);
COPY complete_cast FROM 'complete_cast.csv' WITH (FORMAT csv);
COPY info_type FROM 'info_type.csv' WITH (FORMAT csv);
COPY keyword FROM 'keyword.csv' WITH (FORMAT csv);
COPY kind_type FROM 'kind_type.csv' WITH (FORMAT csv);
COPY link_type FROM 'link_type.csv' WITH (FORMAT csv);
COPY movie_companies FROM 'movie_companies.csv' WITH (FORMAT csv);
COPY movie_info FROM 'movie_info.csv' WITH (FORMAT csv);
COPY movie_info_idx FROM 'movie_info_idx.csv' WITH (FORMAT csv);
COPY movie_keyword FROM 'movie_keyword.csv' WITH (FORMAT csv);
COPY movie_link FROM 'movie_link.csv' WITH (FORMAT csv);
COPY name FROM 'name.csv' WITH (FORMAT csv);
COPY person_info FROM 'person_info.csv' WITH (FORMAT csv);
COPY role_type FROM 'role_type.csv' WITH (FORMAT csv);
COPY title FROM 'title.csv' WITH (FORMAT csv);
